// resources/js/svelte/pages/settings/profile.svelte
<script lang="ts">
    import { router } from '@inertiajs/svelte';
    import { page } from '@inertiajs/svelte';
    import Button from '@/components/ui/Button.svelte';
    import Input from '@/components/ui/Input.svelte';
    import Label from '@/components/ui/Label.svelte';
    import Separator from '@/components/ui/Separator.svelte';
    import type { User } from '@/types';

    let name = $state('');
    let email = $state('');
    let processing = $state(false);

    let {
        mustVerifyEmail = false,
        hasUnverifiedEmail = false,
        status,
    }: {
        mustVerifyEmail?: boolean;
        hasUnverifiedEmail?: boolean;
        status?: string | null;
    } = $props();

    const user = $derived(page.props.auth.user as User);

    $effect(() => {
        if (user) {
            name = user.name;
            email = user.email;
        }
    });

    function submit(e: Event): void {
        e.preventDefault();
        processing = true;
        router.put('/svelte/settings/profile', { name, email }, {
            preserveScroll: true,
            onFinish: () => { processing = false; },
        });
    }

    function sendVerification(): void {
        router.post('/svelte/settings/email/verification-notification', {}, {
            preserveScroll: true,
        });
    }
</script>
<div>
    <div class="space-y-0.5">
        <h2 class="text-xl font-semibold tracking-tight text-foreground">Profile</h2>
        <p class="text-sm text-muted-foreground">Update your name and email address</p>
    </div>

    <Separator class="my-6" />

    <form onsubmit={submit} class="space-y-6">
        <div class="space-y-2">
            <Label for="name">Name</Label>
            <Input id="name" type="text" bind:value={name} required autocomplete="name" />
        </div>

        <div class="space-y-2">
            <Label for="email">Email</Label>
            <Input id="email" type="email" bind:value={email} required autocomplete="email" />
        </div>

        {#if mustVerifyEmail && hasUnverifiedEmail}
            <div class="space-y-2">
                <p class="text-sm text-muted-foreground">
                    Your email address is unverified.
                    <button type="button" class="text-foreground hover:underline" onclick={sendVerification}>
                        Click here to re-send the verification email.
                    </button>
                </p>

                {#if status === 'Verification link sent!'}
                    <p class="text-sm text-green-600 dark:text-green-400">A new verification link has been sent.</p>
                {/if}
            </div>
        {/if}

        <div class="flex items-center gap-4">
            <Button type="submit" disabled={processing}>
                {processing ? 'Saving...' : 'Save'}
            </Button>
        </div>
    </form>
</div>

// resources/js/vue/pages/settings/Profile.vue
<script setup lang="ts">
import { Form, Head, usePage } from '@inertiajs/vue3';
/* @chisel-email-verification */
import { Link } from '@inertiajs/vue3';
/* @end-chisel-email-verification */
import { computed } from 'vue';
import ProfileController from '@/actions/App/Http/Controllers/Vue/ProfileController';
import DeleteUser from '@/components/DeleteUser.vue';
import Heading from '@/components/Heading.vue';
import InputError from '@/components/InputError.vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { edit } from '@/routes/vue/profile';
/* @chisel-email-verification */
import { send } from '@/routes/vue/verification';
/* @end-chisel-email-verification */

defineOptions({
    layout: {
        breadcrumbs: [
            {
                title: 'Profile settings',
                href: edit(),
            },
        ],
    },
});

const page = usePage();
const user = computed(() => page.props.auth.user);
</script>

<template>
    <Head title="Profile settings" />

    <h1 class="sr-only">Profile settings</h1>

    <div class="flex flex-col space-y-6">
        <Heading
            variant="small"
            title="Profile"
            description="Update your name and email address"
        />

        <Form
            v-bind="ProfileController.update.form()"
            class="space-y-6"
            v-slot="{ errors, processing }"
        >
            <div class="grid gap-2">
                <Label for="name">Name</Label>
                <Input
                    id="name"
                    class="mt-1 block w-full"
                    name="name"
                    :default-value="user.name"
                    required
                    autocomplete="name"
                    placeholder="Full name"
                />
                <InputError class="mt-2" :message="errors.name" />
            </div>

            <div class="grid gap-2">
                <Label for="email">Email address</Label>
                <Input
                    id="email"
                    type="email"
                    class="mt-1 block w-full"
                    name="email"
                    :default-value="user.email"
                    required
                    autocomplete="username"
                    placeholder="Email address"
                />
                <InputError class="mt-2" :message="errors.email" />
            </div>

            <!-- @chisel-email-verification -->
            <div v-if="page.props.mustVerifyEmail && !user.email_verified_at">
                <p class="-mt-4 text-sm text-muted-foreground">
                    Your email address is unverified.
                    <Link
                        :href="send()"
                        as="button"
                        class="text-foreground underline decoration-neutral-300 underline-offset-4 transition-colors duration-300 ease-out hover:decoration-current! dark:decoration-neutral-500"
                    >
                        Click here to re-send the verification email.
                    </Link>
                </p>

                <div
                    v-if="page.props.status === 'verification-link-sent'"
                    class="mt-2 text-sm font-medium text-green-600"
                >
                    A new verification link has been sent to your email address.
                </div>
            </div>
            <!-- @end-chisel-email-verification -->

            <div class="flex items-center gap-4">
                <Button :disabled="processing" data-test="update-profile-button"
                    >Save</Button
                >
            </div>
        </Form>
    </div>

    <DeleteUser />
</template>
