// resources/js/react/pages/settings/security.tsx
import { Form, Head } from '@inertiajs/react';
import { useRef } from 'react';
import SecurityController from '@/actions/App/Http/Controllers/React/SecurityController';
import Heading from '@/components/heading';
import InputError from '@/components/input-error';
import PasswordInput from '@/components/password-input';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { edit } from '@/routes/react/security';
/* @chisel-passkeys */
import type { Props as ManagePasskeysProps } from '@/components/manage-passkeys';
import ManagePasskeys from '@/components/manage-passkeys';
/* @end-chisel-passkeys */
/* @chisel-2fa */
import type { Props as ManageTwoFactorProps } from '@/components/manage-two-factor';
import ManageTwoFactor from '@/components/manage-two-factor';
/* @end-chisel-2fa */

type Props = {
    passwordRules: string;
} /* @chisel-passkeys */ & ManagePasskeysProps /* @end-chisel-passkeys */ /* @chisel-2fa */ &
    ManageTwoFactorProps /* @end-chisel-2fa */;

export default function Security(props: Props) {
    const passwordInput = useRef<HTMLInputElement>(null);
    const currentPasswordInput = useRef<HTMLInputElement>(null);

    return (
        <>
            <Head title="Security settings" />

            <h1 className="sr-only">Security settings</h1>

            <div className="space-y-6">
                <Heading
                    variant="small"
                    title="Update password"
                    description="Ensure your account is using a long, random password to stay secure"
                />

                <Form
                    {...SecurityController.update.form()}
                    options={{
                        preserveScroll: true,
                    }}
                    resetOnError={[
                        'password',
                        'password_confirmation',
                        'current_password',
                    ]}
                    resetOnSuccess
                    onError={(errors) => {
                        if (errors.password) {
                            passwordInput.current?.focus();
                        }

                        if (errors.current_password) {
                            currentPasswordInput.current?.focus();
                        }
                    }}
                    className="space-y-6"
                >
                    {({ errors, processing }) => (
                        <>
                            <div className="grid gap-2">
                                <Label htmlFor="current_password">
                                    Current password
                                </Label>

                                <PasswordInput
                                    id="current_password"
                                    ref={currentPasswordInput}
                                    name="current_password"
                                    className="mt-1 block w-full"
                                    autoComplete="current-password"
                                    placeholder="Current password"
                                />

                                <InputError message={errors.current_password} />
                            </div>

                            <div className="grid gap-2">
                                <Label htmlFor="password">New password</Label>

                                <PasswordInput
                                    id="password"
                                    ref={passwordInput}
                                    name="password"
                                    className="mt-1 block w-full"
                                    autoComplete="new-password"
                                    placeholder="New password"
                                    passwordrules={props.passwordRules}
                                />

                                <InputError message={errors.password} />
                            </div>

                            <div className="grid gap-2">
                                <Label htmlFor="password_confirmation">
                                    Confirm password
                                </Label>

                                <PasswordInput
                                    id="password_confirmation"
                                    name="password_confirmation"
                                    className="mt-1 block w-full"
                                    autoComplete="new-password"
                                    placeholder="Confirm password"
                                    passwordrules={props.passwordRules}
                                />

                                <InputError
                                    message={errors.password_confirmation}
                                />
                            </div>

                            <div className="flex items-center gap-4">
                                <Button
                                    disabled={processing}
                                    data-test="update-password-button"
                                >
                                    Save
                                </Button>
                            </div>
                        </>
                    )}
                </Form>
            </div>

            {/* @chisel-2fa */}
            <ManageTwoFactor
                canManageTwoFactor={props.canManageTwoFactor}
                requiresConfirmation={props.requiresConfirmation}
                twoFactorEnabled={props.twoFactorEnabled}
            />
            {/* @end-chisel-2fa */}

            {/* @chisel-passkeys */}
            <ManagePasskeys
                canManagePasskeys={props.canManagePasskeys}
                passkeys={props.passkeys}
            />
            {/* @end-chisel-passkeys */}
        </>
    );
}

Security.layout = {
    breadcrumbs: [
        {
            title: 'Security settings',
            href: edit(),
        },
    ],
};

// resources/js/svelte/pages/settings/security.svelte
<script lang="ts">
    import { router } from '@inertiajs/svelte';
    import { page } from '@inertiajs/svelte';
    import Button from '@/components/ui/Button.svelte';
    import Input from '@/components/ui/Input.svelte';
    import Label from '@/components/ui/Label.svelte';
    import Separator from '@/components/ui/Separator.svelte';
    import type { User } from '@/types';

    let currentPassword = $state('');
    let password = $state('');
    let passwordConfirmation = $state('');
    let processing = $state(false);

    const user = $derived(page.props.auth.user as User);

    function updatePassword(e: Event): void {
        e.preventDefault();
        processing = true;
        router.put('/svelte/settings/password', {
            current_password: currentPassword,
            password,
            password_confirmation: passwordConfirmation,
        }, {
            preserveScroll: true,
            onFinish: () => {
                processing = false;
                currentPassword = '';
                password = '';
                passwordConfirmation = '';
            },
        });
    }
</script>
<div class="space-y-8">
    <div>
        <div class="space-y-0.5">
            <h2 class="text-xl font-semibold tracking-tight text-foreground">Update Password</h2>
            <p class="text-sm text-muted-foreground">Ensure your account is using a long, random password</p>
        </div>

        <Separator class="my-6" />

        <form onsubmit={updatePassword} class="space-y-6">
            <div class="space-y-2">
                <Label for="current_password">Current Password</Label>
                <Input id="current_password" type="password" bind:value={currentPassword} required autocomplete="current-password" />
            </div>

            <div class="space-y-2">
                <Label for="password">New Password</Label>
                <Input id="password" type="password" bind:value={password} required autocomplete="new-password" />
            </div>

            <div class="space-y-2">
                <Label for="password_confirmation">Confirm Password</Label>
                <Input id="password_confirmation" type="password" bind:value={passwordConfirmation} required autocomplete="new-password" />
            </div>

            <div class="flex items-center gap-4">
                <Button type="submit" disabled={processing}>
                    {processing ? 'Saving...' : 'Save'}
                </Button>
            </div>
        </form>
    </div>

    <div>
        <div class="space-y-0.5">
            <h2 class="text-xl font-semibold tracking-tight text-foreground">Two-Factor Authentication</h2>
            <p class="text-sm text-muted-foreground">Add additional security to your account</p>
        </div>

        <Separator class="my-6" />

        <p class="text-sm text-muted-foreground">
            Two-factor authentication is managed through your account security settings.
            Visit the main settings page to configure 2FA.
        </p>
    </div>
</div>
