// resources/js/svelte/pages/teams/index.svelte
<script lang="ts">
    import { router } from '@inertiajs/svelte';
    import Button from '@/components/ui/Button.svelte';
    import Badge from '@/components/ui/Badge.svelte';
    import Input from '@/components/ui/Input.svelte';
    import Label from '@/components/ui/Label.svelte';
    import Separator from '@/components/ui/Separator.svelte';
    import type { Team } from '@/types';

    let teams = $state<Team[]>([]);
    let newTeamName = $state('');
    let creating = $state(false);

    let { teams: initialTeams }: { teams: Team[] } = $props();

    $effect(() => {
        teams = initialTeams;
    });

    function createTeam(e: Event): void {
        e.preventDefault();
        creating = true;
        router.post('/svelte/settings/teams', { name: newTeamName }, {
            onFinish: () => {
                creating = false;
                newTeamName = '';
            },
        });
    }
</script>
<div>
    <div class="space-y-0.5">
        <h2 class="text-xl font-semibold tracking-tight text-foreground">Teams</h2>
        <p class="text-sm text-muted-foreground">Manage your team memberships</p>
    </div>

    <Separator class="my-6" />

    <div class="space-y-6">
        <div class="space-y-4">
            <h3 class="text-lg font-medium text-foreground">Your Teams</h3>

            {#if teams.length === 0}
                <p class="text-sm text-muted-foreground">You don't belong to any teams yet.</p>
            {:else}
                <div class="space-y-2">
                    {#each teams as team (team.id)}
                        <div class="flex items-center justify-between rounded-lg border border-border p-4">
                            <div class="space-y-1">
                                <div class="flex items-center gap-2">
                                    <span class="font-medium text-foreground">{team.name}</span>
                                    {#if team.isPersonal}
                                        <Badge variant="secondary">Personal</Badge>
                                    {/if}
                                    {#if team.isCurrent}
                                        <Badge>Current</Badge>
                                    {/if}
                                </div>
                                <p class="text-sm text-muted-foreground">Role: {team.roleLabel || 'Member'}</p>
                            </div>

                            <div class="flex gap-2">
                                <Button variant="outline" size="sm" onclick={() => router.visit(`/svelte/settings/teams/${team.slug}`)}>
                                    Settings
                                </Button>
                            </div>
                        </div>
                    {/each}
                </div>
            {/if}
        </div>

        <div class="space-y-4">
            <h3 class="text-lg font-medium text-foreground">Create New Team</h3>

            <form onsubmit={createTeam} class="flex gap-2">
                <div class="flex-1 space-y-2">
                    <Label for="team-name">Team Name</Label>
                    <Input id="team-name" type="text" bind:value={newTeamName} placeholder="Acme Corp" required />
                </div>
                <div class="flex items-end">
                    <Button type="submit" disabled={creating || !newTeamName}>
                        {creating ? 'Creating...' : 'Create'}
                    </Button>
                </div>
            </form>
        </div>
    </div>
</div>

// resources/js/react/pages/teams/index.tsx
import { Head, Link } from '@inertiajs/react';
import { Eye, Pencil, Plus } from 'lucide-react';
import CreateTeamModal from '@/components/create-team-modal';
import Heading from '@/components/heading';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
    Tooltip,
    TooltipContent,
    TooltipProvider,
    TooltipTrigger,
} from '@/components/ui/tooltip';
import { edit, index } from '@/routes/react/teams';
import type { Team } from '@/types';

type Props = {
    teams: Team[];
};

export default function TeamsIndex({ teams }: Props) {
    return (
        <>
            <Head title="Teams" />

            <h1 className="sr-only">Teams</h1>

            <div className="flex flex-col space-y-6">
                <div className="flex items-center justify-between">
                    <Heading
                        variant="small"
                        title="Teams"
                        description="Manage your teams and team memberships"
                    />

                    <CreateTeamModal>
                        <Button data-test="teams-new-team-button">
                            <Plus /> New team
                        </Button>
                    </CreateTeamModal>
                </div>

                <div className="space-y-3">
                    {teams.map((team) => (
                        <div
                            key={team.id}
                            data-test="team-row"
                            className="flex items-center justify-between rounded-lg border p-4"
                        >
                            <div className="flex items-center gap-4">
                                <div>
                                    <div className="flex items-center gap-2">
                                        <span className="font-medium">
                                            {team.name}
                                        </span>
                                        {team.isPersonal ? (
                                            <Badge variant="secondary">
                                                Personal
                                            </Badge>
                                        ) : null}
                                    </div>
                                    <span className="text-sm text-muted-foreground">
                                        {team.roleLabel}
                                    </span>
                                </div>
                            </div>

                            <TooltipProvider>
                                <div className="flex items-center gap-2">
                                    {team.role === 'member' ? (
                                        <Tooltip>
                                            <TooltipTrigger asChild>
                                                <Button
                                                    variant="ghost"
                                                    size="sm"
                                                    data-test="team-view-button"
                                                    asChild
                                                >
                                                    <Link
                                                        href={edit(team.slug)}
                                                    >
                                                        <Eye className="h-4 w-4" />
                                                    </Link>
                                                </Button>
                                            </TooltipTrigger>
                                            <TooltipContent>
                                                <p>View team</p>
                                            </TooltipContent>
                                        </Tooltip>
                                    ) : (
                                        <Tooltip>
                                            <TooltipTrigger asChild>
                                                <Button
                                                    variant="ghost"
                                                    size="sm"
                                                    data-test="team-edit-button"
                                                    asChild
                                                >
                                                    <Link
                                                        href={edit(team.slug)}
                                                    >
                                                        <Pencil className="h-4 w-4" />
                                                    </Link>
                                                </Button>
                                            </TooltipTrigger>
                                            <TooltipContent>
                                                <p>Edit team</p>
                                            </TooltipContent>
                                        </Tooltip>
                                    )}
                                </div>
                            </TooltipProvider>
                        </div>
                    ))}

                    {teams.length === 0 ? (
                        <p className="py-8 text-center text-muted-foreground">
                            You don't belong to any teams yet.
                        </p>
                    ) : null}
                </div>
            </div>
        </>
    );
}

TeamsIndex.layout = {
    breadcrumbs: [
        {
            title: 'Teams',
            href: index(),
        },
    ],
};
